/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package reclusos;

import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.*;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.*;
/**
 *
 * @author FAROL
 */
public class CartaAntecedentesNoPenales extends javax.swing.JFrame {

    /**
     * Creates new form CartasAntecedentesNoPenales
     */
    public CartaAntecedentesNoPenales(ExpedirCarta ec) {
        initComponents();
        setLocationRelativeTo(null);
        this.ec = ec;
        fuente = new Font(Font.FontFamily.COURIER, 12, Font.NORMAL);
        fuenteBold = new Font(Font.FontFamily.COURIER, 22, Font.BOLD);
        fuenteItalica = new Font(Font.FontFamily.COURIER, 10, Font.ITALIC);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        campoNombre = new javax.swing.JTextField();
        campoApellidos = new javax.swing.JTextField();
        campoCurp = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel1.setText("Carta de Antecedentes No Penales");

        jLabel2.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel2.setText("Nombre");

        jLabel3.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel3.setText("Apellidos");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 14)); // NOI18N
        jLabel4.setText("CURP");

        jButton1.setText("Crear");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Regresar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(35, 35, 35)
                                .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(campoApellidos)
                                    .addComponent(campoCurp))))))
                .addContainerGap(34, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(109, 109, 109)
                .addComponent(jButton2)
                .addGap(106, 106, 106))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(campoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(campoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(campoCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        CartaAntecedentesNoPenales.this.dispose();
        ec.show();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        crearCarta(evt);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void crearCarta(java.awt.event.ActionEvent evt) {
        nombre = campoNombre.getText().trim();
        apellidos = campoApellidos.getText().trim();
        curp = campoCurp.getText().trim();
        
        if(nombre.equals("") || apellidos.equals("") || curp.equals("") || curp.length() > 18) {
            //System.out.println("Error");
            borrado();
            CartaAntecedentesNoPenales.this.dispose();
            new ExpedicionCartaFallida(CartaAntecedentesNoPenales.this).show();
        } else {
            generarCartas(evt);
        }
    }
    
       private void generarCartas(java.awt.event.ActionEvent evt) {
        JFileChooser jf = new JFileChooser();
        jf.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        jf.requestFocus();
        int r = jf.showOpenDialog(CartaAntecedentesNoPenales.this);
        
        if(r == JFileChooser.APPROVE_OPTION) {
            File f = jf.getSelectedFile();
            String ruta = f.getPath();
            
            try {
                Document doc = new Document(PageSize.A4);
                PdfWriter.getInstance(doc, new FileOutputStream(ruta + "/" + curp + ".pdf"));
                doc.open();
                
                Image imagen = Image.getInstance("./src/imgs/Escudo.jpg");
                imagen.scaleAbsolute(600, 125);
                imagen.setAlignment(Element.ALIGN_CENTER);
                doc.add(imagen);
                doc.add(getCabecera(CABECERA, curp));
                doc.add(getInfo(CUERPO));
                doc.add(getFirmas(colocarFirmas()));
                doc.add(getFooter(FOOTER));
                doc.close();
                
                JOptionPane.showMessageDialog(CartaAntecedentesNoPenales.this, "Carta Guardada en " + ruta);
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        
        borrado();
    }
 
    private Paragraph getCabecera(String texto, String curp) {
        
        texto += "\n\nC. " + nombre + " " + apellidos + "\n\n"
                + "Con el siguiente CURP \n\n" + curp +"\n\n";  
            
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_CENTER);
        c.append(texto);
        c.setFont(fuenteBold);
        p.add(c);
        
        return p;
    }
    
      private Paragraph getInfo(String texto) {
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_CENTER);
        c.append(texto);
        c.setFont(fuente);
        p.add(c);
        
        return p;
    }
      
      private Paragraph getFooter(String texto) {
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_RIGHT);
        c.append(texto);
        c.setFont(fuenteItalica);
        p.add(c);
        
        return p;
    }
    
    private Paragraph getFirmas(String texto) {
        Paragraph p = new Paragraph();
        Chunk c = new Chunk();
        p.setAlignment(Element.ALIGN_CENTER);
        c.append(texto);
        c.setFont(fuente);
        p.add(c);
        
        return p;
    }  

     private String colocarFirmas() {
        String formato = "\n\n"
                + "_________________________________________________"
                + "\n\n"
                + "Director General del Reclusorio";
     
        return formato;
    }
     
    private void borrado() {
        campoNombre.setText("");
        campoApellidos.setText("");
        campoCurp.setText("");
    }
    
    private ExpedirCarta ec;
    private String nombre;
    private String apellidos;
    private String curp;
    private Font fuenteBold;
    private Font fuente;
    private Font fuenteItalica;
    
    private final String CABECERA = ""
            + "\n\nSe otorga la siguiente Carta de Antecedentes No Penales al"
            + "";
    
    private final String FOOTER = ""
            + "Analisis y Diseño Orientado a Objetos, 2CM9, 2019"
            + "";
    
    private final String CUERPO = "\n\n"
            + "Dando Fe que es un ciudadano integro, que respeta la ley\n\n"
            + "y busca el bien del projimo para llevar una vida armoniosa\n\n"
            + "Dando total confianza en el ciudadano ya antes mencionado\n\n"
            + "Para su optimo desarrollo en la sociedad\n\n\n\n\n\n\n\n";
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoApellidos;
    private javax.swing.JTextField campoCurp;
    private javax.swing.JTextField campoNombre;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}
